Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install firefox -y
choco install brave -y
choco install googlechrome -y
choco install spotify -y
choco install telegram -y
choco install git -y
choco install nodejs -y
choco install dbeaver -y
choco install vscode -y
choco install ditto -y
choco install 7zip -y
choco install notepadplusplus -y
choco install vlc -y
choco install ccleaner -y
choco install teamviewer -y
choco install thunderbird -y
choco install k-litecodecpackfull -y
choco install yarn -y
choco install microsoft-windows-terminal -y
choco install docker-desktop -y
choco install hyper -y
choco install notion -y
choco install rocketchat -y
choco install insomnia-rest-api-client -y
choco install revo-uninstaller -y
choco install wsl2 -y
choco install wsl-ubuntu-2004 -y
